#!/usr/bin/env bash

factorize() {
    n=$1
    for ((i = 2; i <= n; i++)); do
        if ((n % i == 0)); then
            echo "$n=$i*$(($n / $i))"
            return
        fi
    done
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
fi

while read -r line; do
    factorize "$line"
done < "$1"
