#!/usr/bin/python3

import math

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

def factorize_to_primes(n):
    for i in range(2, n + 1):
        if is_prime(i) and n % i == 0:
            return i, n // i

if __name__ == '__main__':
    import sys
    if len(sys.argv) != 2:
        print("Usage: python rsa.py <file>")
        sys.exit(1)
    file_path = sys.argv[1]

    with open(file_path, 'r') as file:
        n = int(file.readline().strip())
        p, q = factorize_to_primes(n)
        print(f'{n}={p}*{q}')
